Repository jupyterhub/jupyter-server-proxy, pull requests merged in 2021-11, with the labels that each got.

#301 Class-based rewrite response
  jupyter_server_proxy/config.py
  jupyter_server_proxy/handlers.py
  tests/resources/jupyter_server_config.py
  tests/test_proxies.py
Labels: enhancement

#304 Set reason according to response code
  jupyter_server_proxy/config.py
  jupyter_server_proxy/handlers.py
  tests/resources/jupyter_server_config.py
  tests/test_proxies.py
Labels: bug

#303 Add changelog for 3.1.0 (already released) and 3.2.0 (unreleased)
  CHANGELOG.md
  jupyter_server_proxy/config.py
Labels: documentation

#298 Test with lab
  .github/workflows/test.yaml
  CONTRIBUTING.md
Labels: ci

#307 resolve yarn.lock, bump builder version, some packaging metadata
  .github/workflows/test.yaml
  jupyter_server_proxy/__init__.py
  jupyterlab-server-proxy/package.json
  jupyterlab-server-proxy/yarn.lock
  setup.py
Labels: maintenance, dependencies

#310 ci: avoid triggering ci twice on pre-commit.ci/dependabot prs
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: ci

#311 Update language, from master to main
  contrib/template/{{cookiecutter.project_name}}/setup.py
  contrib/theia/setup.py
  docs/conf.py
  jupyter_server_proxy/utils.py
Labels: maintenance

#312 Remove no longer needed logic involving six
  jupyter_server_proxy/utils.py
Labels: maintenance
