Repository jupyterhub/jupyter-server-proxy, pull requests merged in 2022-11, with the labels that each got.

#344 Fix config filename in config via traitlets doc
  docs/server-process.rst
Labels: documentation

#348 ci: test against modern python versions and fix broken test suite
  .github/workflows/test.yaml
  tests/acceptance/Classic.robot
  tests/acceptance/Lab.robot
  tests/acceptance/__init__.robot
  tests/acceptance/test_acceptance.py
Labels: ci

#350 Drop support for Python 3.6
  .github/workflows/test.yaml
  setup.py
Labels: maintenance, breaking

#351 ci: update github actions, small refactors, add dependabot for gha
  .github/dependabot.yaml
  .github/workflows/linkcheck.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  .readthedocs.yaml
  docs/conf.py
Labels: ci

#352 docs: switch from alabaster to sphinx-book-theme, and misc docs build system maintenance
  .readthedocs.yaml
  README.md
  RELEASE.md
  docs/Makefile
  docs/conf.py
  docs/convenience/packages/theia.rst
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/images/labextension-launcher.png
  docs/source/_static/images/logo/favicon.ico
  docs/source/_static/images/nbextension-tree.png
  docs/source/arbitrary-ports-hosts.rst
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/contributing/release.rst
  docs/source/convenience/new.rst
  docs/source/convenience/packages/theia.rst
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/launchers.rst
  docs/source/server-process.rst
Labels: documentation

#353 Refine RELEASE.md with tbump
  RELEASE.md
  pyproject.toml
Labels: maintenance

#355 Update labextension build
  .github/workflows/test.yaml
  .gitignore
  CONTRIBUTING.md
  jupyterlab-server-proxy/.yarnrc
  jupyterlab-server-proxy/LICENSE
  jupyterlab-server-proxy/README.md
  jupyterlab-server-proxy/package.json
  jupyterlab-server-proxy/tsconfig.json
  jupyterlab-server-proxy/yarn.lock
Labels: maintenance
