Repository jupyterhub/jupyter-server-proxy, pull requests merged in 2023-01, with the labels that each got.

#339 Accept an unset `command` to proxy to an already started process (unmanaged process)
  docs/source/server-process.rst
  jupyter_server_proxy/config.py
  jupyter_server_proxy/handlers.py
  tests/resources/jupyter_server_config.py
  tests/test_proxies.py
Labels: new

#366 Fix tests against jupyter_server 2
  .github/workflows/test.yaml
  setup.py
  tests/acceptance/__init__.robot
  tests/acceptance/resources/jupyter_config.json
  tests/acceptance/test_acceptance.py
Labels: ci

#368 Rename @jupyterlab/server-proxy to @jupyterhub/jupyter-server-proxy
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  CONTRIBUTING.md
  MANIFEST.in
  README.md
  RELEASE.md
  docs/source/launchers.rst
  labextension/.gitignore
  labextension/.yarnrc
  labextension/LICENSE
  labextension/README.md
  labextension/package.json
  labextension/src/index.ts
  labextension/tsconfig.json
  labextension/yarn.lock
  pyproject.toml
  setup.py
Labels: maintenance, breaking, code:jupyterlab-extension

#371 Adopt hatchling, plugins for python package build
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  jupyter_server_proxy/etc/jupyter_notebook_config.d/jupyter-server-proxy.json
  jupyter_server_proxy/etc/jupyter_server_config.d/jupyter-server-proxy.json
  jupyter_server_proxy/etc/nbconfig/tree.d/jupyter-server-proxy.json
  labextension/README.md
  labextension/package.json
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#375 Fix imshields link README.md
  README.md
Labels: documentation
