Repository jupyterhub/jupyter-server-proxy, pull requests merged in 2023-04, with the labels that each got.

#385 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#337 Support proxying to a server process via a Unix socket
  docs/source/server-process.rst
  jupyter_server_proxy/config.py
  jupyter_server_proxy/handlers.py
  jupyter_server_proxy/unixsock.py
  jupyter_server_proxy/websocket.py
  tests/resources/httpinfo.py
  tests/resources/jupyter_server_config.py
  tests/test_proxies.py
Labels: new

#391 Fix editable install and update CONTRIBUTING.md
  .gitignore
  CONTRIBUTING.md
  jupyter_server_proxy/__init__.py
  pyproject.toml
Labels: maintenance

#390 pre-commit: add config and small fixes
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  contrib/code-server-traitlet/jupyter_notebook_config.py
  contrib/template/cookiecutter.json
  contrib/template/{{cookiecutter.project_name}}/jupyter_{{cookiecutter.project_name}}_proxy/__init__.py
  contrib/theia/jupyter_theia_proxy/__init__.py
  contrib/theia/setup.py
  docs/source/arbitrary-ports-hosts.rst
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/convenience/new.rst
  jupyter_server_proxy/__init__.py
  jupyter_server_proxy/api.py
  jupyter_server_proxy/config.py
  jupyter_server_proxy/etc/nbconfig/tree.d/jupyter-server-proxy.json
  jupyter_server_proxy/handlers.py
  jupyter_server_proxy/static/tree.js
  jupyter_server_proxy/unixsock.py
  jupyter_server_proxy/utils.py
  jupyter_server_proxy/websocket.py
  labextension/src/index.ts
  pyproject.toml
  tests/acceptance/test_acceptance.py
  tests/resources/gzipserver.py
  tests/resources/httpinfo.py
  tests/resources/jupyter_server_config.py
  tests/resources/proxyextension.py
  tests/resources/websocket.py
  tests/test_config.py
  tests/test_proxies.py
  tests/test_utils.py
Labels: maintenance

#396 Use `pytest.fixture`s for starting servers, use `importlib*metadata`
  .github/workflows/test.yaml
  CONTRIBUTING.md
  jupyter_server_proxy/__init__.py
  jupyter_server_proxy/config.py
  pyproject.toml
  tests/conftest.py
  tests/pytest.ini
  tests/resources/jupyter_server_config.py
  tests/test_proxies.py
Labels: bug, maintenance

#393 docs: convert .rst to MyST based markdown files
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  docs/source/arbitrary-ports-hosts.md
  docs/source/arbitrary-ports-hosts.rst
  docs/source/conf.py
  docs/source/convenience/new.md
  docs/source/convenience/new.rst
  docs/source/convenience/packages/theia.md
  docs/source/convenience/packages/theia.rst
  docs/source/examples.md
  docs/source/examples.rst
  docs/source/index.md
  docs/source/index.rst
  docs/source/install.md
  docs/source/install.rst
  docs/source/launchers.md
  docs/source/server-process.md
  docs/source/server-process.rst
Labels: documentation

#394 maint, breaking: drop support for jupyterlab 2
  .github/workflows/test.yaml
  CONTRIBUTING.md
  README.md
  docs/source/launchers.md
  pyproject.toml
Labels: maintenance, breaking

#398 maint: update package description to not claim windows support
  pyproject.toml
Labels: maintenance

#401 ci: cleanup stashed SHA256 checksum before publish to PyPI
  .github/workflows/publish.yaml
Labels: ci
