Repository jupyterhub/jupyter-server-proxy, pull requests merged in 2024-06, with the labels that each got.

#481 Fix failure to update __version__
  jupyter_server_proxy/_version.py
  pyproject.toml
Labels: bug

#483 ci: fix test failure on windows and error on bash pipe failures etc
  .github/workflows/test.yaml
Labels: ci

#484 ci: reference node lts to avoid need to bump in october
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: ci

#485 ci: remove workaround running test in py311 instead of py312
  .github/workflows/test.yaml
Labels: ci

#447 Add `raw_socket_proxy` to directly proxy websockets to TCP/unix sockets
  docs/source/server-process.md
  jupyter_server_proxy/config.py
  jupyter_server_proxy/rawsocket.py
  tests/resources/jupyter_server_config.py
  tests/resources/rawsocket.py
  tests/test_proxies.py
Labels: enhancement
